name = "java"
title = "Java"
intersphinx = ["https://mongodb.com/docs/manual/objects.inv",
               "https://mongodb.com/docs/drivers/objects.inv"]
toc_landing_pages = [
    "/fundamentals/connection",
    "/fundamentals/crud",
    "/fundamentals/builders",
    "/usage-examples"
]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
version = 4.3
full-version = "{+version+}.4"
mdb-server = "MongoDB Server"

package-name-org = "mongodb-org"
api = "https://mongodb.github.io/mongo-java-driver/{+version+}"
stable-api = "Stable API"

[[banners]]
targets = ["*"]
variant = "info"
value = """\
    This version of the documentation is archived and no longer supported. View the `current documentation <https://www.mongodb.com/docs/drivers/java/sync/current/>`__ to learn how to `upgrade your version of the Java Sync Driver <https://www.mongodb.com/docs/drivers/java/sync/current/upgrade/>`__.\
    """
